---
###############################################################################
# Manager Calibre Users
###############################################################################
# Check if user exists and create if enabled.
#
# Args:
#   calibre_user: str calibre username.
#   calibre_group: str calibre group.
#   calibre_create_user: boolean true to create role default user.
#   calibre_default_user: dict containing builitin.user options for calibre.
#   calibre_default_group: dict containing builitin.group options for calibre.

- name: 'manage users | confirm user exists'
  ansible.builtin.command: 'id {{ calibre_user }}'
  register: _calibre_user_exists
  changed_when: _calibre_user_exists.rc > 0
  failed_when: false

- name: 'manage users | confirm group exists'
  ansible.builtin.command: 'groups {{ calibre_group }}'
  register: _calibre_group_exists
  changed_when: _calibre_group_exists.rc > 0
  failed_when: false

- name: 'manage users | create calibre group'
  ansible.builtin.group:
    name:  '{{ calibre_default_group.name }}'
    gid:   '{{ calibre_default_group.gid }}'
    state: 'present'
  when: calibre_create_user and _calibre_group_exists.rc != 0

- name: 'manage users | create calibre user (logins disabled)'
  ansible.builtin.user:
    name:            '{{ calibre_default_user.name }}'
    group:           '{{ calibre_default_user.group }}'
    uid:             '{{ calibre_default_user.uid }}'
    shell:           '{{ calibre_default_user.shell }}'
    home:            '{{ calibre_default_user.home }}'
    comment:         '{{ calibre_default_user.comment }}'
    create_home:     '{{ calibre_default_user.create_home }}'
    password:        '{{ calibre_default_user.password }}'
    password_lock:   '{{ calibre_default_user.password_lock }}'
    update_password: '{{ calibre_default_user.update_password }}'
    expires:         '{{ calibre_default_user.expires }}'
    system:          '{{ calibre_default_user.system }}'
    state:           'present'
  when: calibre_create_user and _calibre_user_exists.rc != 0
