---
###############################################################################
# Calibre Configuration
###############################################################################
# Configure Calibre and calibre-web.
#
# Args:
#   _calibre_web_target_dir: str versioned install directory (full path).
#   _calibre_web_dir: str unversioned install directory (full path).
#   _calibre_web_app_db_source: str source location of calibre app.db.
#
# Reference:
# * https://github.com/janeczku/calibre-web/wiki/Command-Line-Interface
# * https://github.com/janeczku/calibre-web/wiki/Setup-Service-on-Linux#start-calibre-web-as-service-under-linux-with-systemd

- name: 'web config | create /var/log/calibre'
  ansible.builtin.file:
    path:  '/var/log/calibre'
    owner: '{{ calibre_user }}'
    group: '{{ calibre_group }}'
    mode:  0750
    state: 'directory'

- name: 'web config | link calibre-web versioned directory'
  ansible.builtin.file:
    src:   '{{ _calibre_web_target_dir }}'
    dest:  '{{ _calibre_web_dir }}'
    owner: 'root'
    group: '{{ calibre_group }}'
    mode:  0750
    state: 'link'
  changed_when: false

- name: 'web config | check for calibre-web app.db in library'
  ansible.builtin.stat:
    path: '{{ calibre_library }}/app.db'
  register: _calibre_web_app_install_stat

- name: 'web config | set inital calibre-web app.db'
  ansible.builtin.copy:
    src:   '{{ _calibre_web_app_db_source }}'
    dest:  '{{ calibre_library }}/app.db'
    owner: '{{ calibre_user }}'
    group: '{{ calibre_group }}'
    mode:  '0600'
  when: not _calibre_web_app_install_stat.stat.exists

- name: 'web config | set /etc/systemd/system/calibre-web.service'
  ansible.builtin.template:
    src:   'calibre-web.service.j2'
    dest:  '/etc/systemd/system/calibre-web.service'
    owner: 'root'
    group: 'root'
    mode:  0644
  notify:
    - 'reload systemd'
