---
- ansible.builtin.include_tasks: core.yml
- ansible.builtin.include_tasks: packages.yml
- ansible.builtin.include_tasks: download.yml
- ansible.builtin.include_tasks: unpack.yml
- ansible.builtin.include_tasks: virtualenv.yml
- ansible.builtin.include_tasks: config.yml
- ansible.builtin.include_tasks: db.yml
- ansible.builtin.include_tasks: clean.yml
