---
###############################################################################
# Calibre-Web Python Virtual Environment
###############################################################################
# Configure Python Virtual Environment. This is created in the versioned
# install location so state is keep between versions. Assumes archive is
# already unpacked and cleaned.
#
# Optional feature requirements (in optional-requirements.txt) have a simple
# '# HEADER' header and a vertical space or EOF to denote end of section.
#
# Args:
#   _calibre_web_venv: str versioned python virtual environment location.
#   _calibre_web_install_dir: str versioned install location.
#
# Reference:
# * https://github.com/janeczku/calibre-web/wiki/How-To:Install-Calibre-Web-in-Linux-Mint-19-or-20

- name: 'web virtualenv | virtual environment configuration (may take a while)'
  ansible.builtin.debug:
    msg: |
      Virtual environment is being configured. This will take a few minutes.

- name: 'web virtualenv | setup virtual environment'
  ansible.builtin.pip:
    virtualenv:         '{{ _calibre_web_venv }}'
    virtualenv_command: 'virtualenv'
    virtualenv_python:  'python3'
    extra_args: '--upgrade'
    name:
      - 'pip'
      - 'setuptools'
      - 'wheel'
  become: true
  become_user: '{{ calibre_user }}'
  # Reference: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true

- name: 'web virtualenv | setup virtual environment (base features)'
  ansible.builtin.pip:
    virtualenv:         '{{ _calibre_web_venv }}'
    virtualenv_command: 'virtualenv'
    virtualenv_python:  'python3'
    requirements:       '{{ _calibre_web_install_dir }}/requirements.txt'
    extra_args:         '--upgrade'
  become: true
  become_user: '{{ calibre_user }}'
  # Reference: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true

- name: 'web virtualenv | setup virtual environment (optional features)'
  ansible.builtin.include_tasks: virtualenv_optional.yml
  vars:
    header:  '{{ item.header }}'
    enabled: '{{ item.enabled }}'
  loop: '{{ _calibre_web_features }}'

- name: 'web virtualenv | secure virtual environment'
  ansible.builtin.file:
    path:    '{{ _calibre_web_venv }}'
    owner:   '{{ calibre_user }}'
    group:   '{{ calibre_group }}'
    mode:    'a-st,g-w,o-rwx'
    state:   'directory'
    recurse: true
