---
###############################################################################
# Calibre Packages
###############################################################################

- name: 'binary packages | add packages (may take a while)'
  ansible.builtin.debug:
    msg: |
      Packages are being installed. This will take a few minutes.

- name: 'binary packages | install core dependencies'
  ansible.builtin.apt:
    name:  '{{ calibre_binary_default_packages }}'
    state: 'latest'
    update_cache: true
  loop:
    - '{{ calibre_binary_default_packages }}'
