---
###############################################################################
# Calibre Unpack Packages
###############################################################################
# Calibre binaries are only extracted to provide tooling for calibre-web.
# Extract Calibre archive to versioned location.
#
# Args:
#   _calibre_install_dir: str versioned install directory (full path).

- name: 'binary unpack | create calibre directory'
  ansible.builtin.file:
    path:  '{{ _calibre_install_dir }}'
    owner: 'root'
    group: '{{ calibre_group }}'
    mode:  0755
    state: 'directory'

- name: 'binary unpack | unpack calibre archive'
  ansible.builtin.unarchive:
    src:     '{{ _calibre_archive }}'
    remote_src: true
    dest:    '{{ _calibre_install_dir }}'
    creates: '{{ _calibre_install_dir }}/calibre-server'
    owner:   '{{ calibre_user }}'
    group:   '{{ calibre_group }}'
    mode:    'o-rwx'
